### ISSUE TITLE
Reading TDS value upto 1000 PPM using ESP wroom 02 wifi module.

### ISSUE THREAD

**Issue by sivaahakatech** [MarkJB/TDS_Sensor#1]
Hello,
               I am currently working on **ESP wroom 02** for TDS reading purpose.  I have TDS sensor at TOUT(ADC pin) of esp wroom 02.  I have  been working with this code and modified for esp wroom 02 with range 0 to 520 ppm.  I want to extend this range up-to 1000 ppm.   
              Upto now I did many changes to getting value up-to 1000 ppm but it could not work, with  Vref and attenuation I achieved 950 PPM but the actual value of TDS is totally different. I have checked this with standard   **TDS meter ( MI company)**. I got too much difference in reading which were not I aspect, so would it be possible to extend this for 1000 ppm. 

The following changes i did in Vref.
**At Vref 1.18V we got upto 520PPM  
At  Verf 1.5V we got upto 720ppm -but  we need 510ppm.
At vref 1.8V we got upto 950 ppm - but we need 710 ppm.**
  
Please suggest me....  

Regards,
Nilesh

[TDSmeter_sensor_comparison_with_our_board.xlsx](https://github.com/MarkJB/TDS_Sensor/files/3176301/TDSmeter_sensor_comparison_with_our_board.xlsx)

**Comment by MarkJB** [comment]
Is this with the DFRobot Gravity TDS sensor board?

**Comment by sivaahakatech** [comment]
Hello ,
        Yes, it is DFRobot Gravity TDS sensor board.

**Comment by MarkJB** [comment]
What ESP-WROOM-02 board are you using?

**Comment by sivaahakatech** [comment]
Hello,
    Please refer this URL AND DATASHEET  "https://www.espressif.com/sites/default/files/documentation/0c-esp-wroom-02_datasheet_en.pdf"
![IMG_20190522_152658](https://user-images.githubusercontent.com/42567429/58165970-71f7ee80-7ca6-11e9-88ae-2b0dddffd78e.jpg)

**Comment by MarkJB** [comment]
FWIW I've read the data sheet but it doesn't say much. 
Some dev boards appear to have resistor dividers to scale the input on 'TOUT'. I don't know which board you are using so don't know if that is affecting what you are seeing.

If this is your own board using that module, I'd suggest you need to implement your own resistor divider to scale the output of the tds sensor to something that ADC can cope with.

**Comment by sivaahakatech** [comment]
I didn't understand where to put voltage divider first because I have  implemented same exact DFRobot board in my ckt.... which mean all component of DFRobot board used with new ckt..
              If i use voltage divider at output of TDS board then its would totally affect the TDS reading because i have checked with this way... 
               Prior to this i have checked with original DFRobot board and compare  with my TDS ckt and it shows same reading.

Schematic of DFRobot has attached.

[Analog TDS Sensor(V1.0) Schematic.pdf](https://github.com/MarkJB/TDS_Sensor/files/3210375/Analog.TDS.Sensor.V1.0.Schematic.pdf)

**Comment by MarkJB** [comment]
If the input scaling on the ESP-WROOM-02 ADC isn't getting you the desired results then you can either add a voltage divider to your circuit or it may be possible to change the values of some of the components in the DFRobot circuit to affect the analogue output voltage.
