### ISSUE TITLE
How to load it?

### ISSUE THREAD

**Issue by realtek2017** [MarkJB/TDS_Sensor#2]
Hi,

How do you load this into ESPHome so I can use it?

Thanks

**Comment by MarkJB** [comment]
I don't know much about ESPHome. It sounds like that installs its own firmware and I don't know how that would be configured to read the TDS sensor.

**Comment by realtek2017** [comment]
Thank you, I just looked up on expressif as I haven't used that before but will have to read up on it and see if I can get it working. This is the only repository I have found anywhere that has ESP support for the SEN0244 so good work!
